Added an MSMQ label length test
MSMQ docs mention a maximum of 250 characters for a message label and
the code takes that into account. Yet when a message label is set to
exactly 250 characters, MSMQ does not like it very much and throws a
MessageQueueException: "One or more of the passed properties are
invalid."